name: my-docker-project

services:
  app:
    build: .
    image: my-app-image
    container_name: my-app-container
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./yallaShoot/.env
    depends_on:
      - redis



  redis:
    image: "redis:alpine"
    container_name: my-redis-container
    restart: unless-stopped
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  redis_data: